# Game Variables
BPM = 70
MAX_HEALTH = 10
NOTES_PER_BRANCH = 12

# Game Window Dimensions
HEIGHT = 600
WIDTH_SCALE = 80
AMOUNT_OF_NOTES = 7
WIDTH = WIDTH_SCALE * AMOUNT_OF_NOTES
PIANO_HEIGHT = 100
TARGET_HEIGHT = 50
DISPLAYED_BEATS = 4
NOTE_DISPLAY_HEIGHT = HEIGHT - PIANO_HEIGHT - (TARGET_HEIGHT * 1.5)

# Note Settings
NOTE_SPEED = NOTE_DISPLAY_HEIGHT / DISPLAYED_BEATS  # Height per beat
NOTE_BEAT_FORGIVENESS = 0.2  # Allowed margin for hitting notes

# MIDI Settings
MIDI = True

# Music File
MUSIC_FILE = "music/backingMain.mp3"

# Score Settings
SCORE_INCREMENT = 10

# Colors
SCREEN_COLOR = (255, 255, 255)
BUTTON_COLOR = (0, 255, 0)
BUTTON_HOVER_COLOR = (0, 186, 0)
BUTTON_TEXT_COLOR = (255, 255, 255)
TITLE_TEXT_COLOR = (0, 0, 0)

# Button Geometry
BUTTON_WIDTH = 230
BUTTON_HEIGHT = 50
BUTTON_X = (WIDTH_SCALE * AMOUNT_OF_NOTES - BUTTON_WIDTH) // 2
BUTTON_Y = (HEIGHT - BUTTON_HEIGHT) // 2
BORDER_WIDTH = 3

# Graphic times
KEY_FLASH_TIME = 30
GHOST_FADE_TIME = 60
CIRCLE_FADE_TIME = 3

# Settings Page
ENABLE_METRONOME = False
CURRENT_BPM = 70
MIDI_DEVICES = []
SELECTED_MIDI_DEVICE = None
MIDI_DROPDOWN_EXPANDED = False
BPM_INPUT_ACTIVE = False
BPM_INPUT_TEXT = str(CURRENT_BPM)
